name: Generate Snake Heatmap

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight UTC
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Aakash-M-z
          outputs: |
            dist/github-contribution-grid-snake-gotham.svg

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Update contribution heatmap" || exit 0
          git push
