
name: Generate Snake Heatmap

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Aakash-M-z
          outputs: |
            dist/github-contribution-grid-snake-gotham.svg

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
